2021-12-05 19:47:20,162 ERROR: Exception on /user/jay [GET] [in /home/jayesh/Desktop/myproj/flask_practice/Miguel_tut/my_env/lib/python3.8/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/home/jayesh/Desktop/myproj/flask_practice/Miguel_tut/my_env/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jayesh/Desktop/myproj/flask_practice/Miguel_tut/my_env/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/jayesh/Desktop/myproj/flask_practice/Miguel_tut/my_env/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jayesh/Desktop/myproj/flask_practice/Miguel_tut/my_env/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/jayesh/Desktop/myproj/flask_practice/Miguel_tut/main_app/routes.py", line 80, in user
    return render_template("user.html", params=locals())
  File "/home/jayesh/Desktop/myproj/flask_practice/Miguel_tut/my_env/lib/python3.8/site-packages/flask/templating.py", line 147, in render_template
    return _render(
  File "/home/jayesh/Desktop/myproj/flask_practice/Miguel_tut/my_env/lib/python3.8/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/home/jayesh/Desktop/myproj/flask_practice/Miguel_tut/my_env/lib/python3.8/site-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/home/jayesh/Desktop/myproj/flask_practice/Miguel_tut/my_env/lib/python3.8/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/jayesh/Desktop/myproj/flask_practice/Miguel_tut/main_app/templates/user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/jayesh/Desktop/myproj/flask_practice/Miguel_tut/main_app/templates/base.html", line 33, in top-level template code
    {% block content %}{% endblock %}
  File "/home/jayesh/Desktop/myproj/flask_practice/Miguel_tut/main_app/templates/user.html", line 17, in block 'content'
    {{ form.hidden_tag() }}
  File "/home/jayesh/Desktop/myproj/flask_practice/Miguel_tut/my_env/lib/python3.8/site-packages/jinja2/environment.py", line 474, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
2021-12-05 19:47:20,312 ERROR: Exception on /user/jay [GET] [in /home/jayesh/Desktop/myproj/flask_practice/Miguel_tut/my_env/lib/python3.8/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/home/jayesh/Desktop/myproj/flask_practice/Miguel_tut/my_env/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jayesh/Desktop/myproj/flask_practice/Miguel_tut/my_env/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/jayesh/Desktop/myproj/flask_practice/Miguel_tut/my_env/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jayesh/Desktop/myproj/flask_practice/Miguel_tut/my_env/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/jayesh/Desktop/myproj/flask_practice/Miguel_tut/main_app/routes.py", line 80, in user
    return render_template("user.html", params=locals())
  File "/home/jayesh/Desktop/myproj/flask_practice/Miguel_tut/my_env/lib/python3.8/site-packages/flask/templating.py", line 147, in render_template
    return _render(
  File "/home/jayesh/Desktop/myproj/flask_practice/Miguel_tut/my_env/lib/python3.8/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/home/jayesh/Desktop/myproj/flask_practice/Miguel_tut/my_env/lib/python3.8/site-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/home/jayesh/Desktop/myproj/flask_practice/Miguel_tut/my_env/lib/python3.8/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/jayesh/Desktop/myproj/flask_practice/Miguel_tut/main_app/templates/user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/jayesh/Desktop/myproj/flask_practice/Miguel_tut/main_app/templates/base.html", line 33, in top-level template code
    {% block content %}{% endblock %}
  File "/home/jayesh/Desktop/myproj/flask_practice/Miguel_tut/main_app/templates/user.html", line 17, in block 'content'
    {{ form.hidden_tag() }}
  File "/home/jayesh/Desktop/myproj/flask_practice/Miguel_tut/my_env/lib/python3.8/site-packages/jinja2/environment.py", line 474, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
2021-12-05 19:47:20,495 ERROR: Exception on /user/jay [GET] [in /home/jayesh/Desktop/myproj/flask_practice/Miguel_tut/my_env/lib/python3.8/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/home/jayesh/Desktop/myproj/flask_practice/Miguel_tut/my_env/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jayesh/Desktop/myproj/flask_practice/Miguel_tut/my_env/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/jayesh/Desktop/myproj/flask_practice/Miguel_tut/my_env/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jayesh/Desktop/myproj/flask_practice/Miguel_tut/my_env/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/jayesh/Desktop/myproj/flask_practice/Miguel_tut/main_app/routes.py", line 80, in user
    return render_template("user.html", params=locals())
  File "/home/jayesh/Desktop/myproj/flask_practice/Miguel_tut/my_env/lib/python3.8/site-packages/flask/templating.py", line 147, in render_template
    return _render(
  File "/home/jayesh/Desktop/myproj/flask_practice/Miguel_tut/my_env/lib/python3.8/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/home/jayesh/Desktop/myproj/flask_practice/Miguel_tut/my_env/lib/python3.8/site-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/home/jayesh/Desktop/myproj/flask_practice/Miguel_tut/my_env/lib/python3.8/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/jayesh/Desktop/myproj/flask_practice/Miguel_tut/main_app/templates/user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/jayesh/Desktop/myproj/flask_practice/Miguel_tut/main_app/templates/base.html", line 33, in top-level template code
    {% block content %}{% endblock %}
  File "/home/jayesh/Desktop/myproj/flask_practice/Miguel_tut/main_app/templates/user.html", line 17, in block 'content'
    {{ form.hidden_tag() }}
  File "/home/jayesh/Desktop/myproj/flask_practice/Miguel_tut/my_env/lib/python3.8/site-packages/jinja2/environment.py", line 474, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
2021-12-05 19:48:49,900 INFO: Microblog startup [in /home/jayesh/Desktop/myproj/flask_practice/Miguel_tut/main_app/__init__.py:37]
2021-12-05 19:49:07,003 INFO: Microblog startup [in /home/jayesh/Desktop/myproj/flask_practice/Miguel_tut/main_app/__init__.py:37]
2021-12-05 19:49:14,153 INFO: Microblog startup [in /home/jayesh/Desktop/myproj/flask_practice/Miguel_tut/main_app/__init__.py:37]
2021-12-05 19:50:32,765 INFO: Microblog startup [in /home/jayesh/Desktop/myproj/flask_practice/Miguel_tut/main_app/__init__.py:37]
2021-12-05 19:52:19,650 INFO: Microblog startup [in /home/jayesh/Desktop/myproj/flask_practice/Miguel_tut/main_app/__init__.py:37]
